# File generated by: write_lattice_in_foreign_format
# Bmad lattice file: /nfs/acc/user/dcs16/linux_lib/test_colocho/lat.bmad

using Beamlines

@eles beggunb = Marker()
@eles dgbca = Drift(L = -7.17050000000000048E-002)
@eles sol1bkb = Solenoid(label = "Bucking Coil", alias = "SOLN:GUNB:100")
@eles dgbcb = Drift(L =  7.17050000000000048E-002)
@eles cathodeb = Drift(alias = "CATH:GUNB:100")
@eles dgun = Drift(L =  4.00000000000000008E-002)
@eles dg001 = Drift(L =  1.63479999999999986E-001)
@eles slave_drift_0_8 = Drift(L =  4.30499999999999911E-002)
@eles sq01b = Multipole(x1_limit = -2.37500000000000003E-00, x2_limit =  2.37500000000000003E-00,
   y1_limit = -2.37500000000000003E-00, y2_limit =  2.37500000000000003E-00, label = "solenoid trim",
   alias = "QUAD:GUNB:212:2")
@eles cq01b = Multipole(x1_limit = -2.37500000000000003E-00, x2_limit =  2.37500000000000003E-00,
   y1_limit = -2.37500000000000003E-00, y2_limit =  2.37500000000000003E-00, label = "solenoid trim",
   alias = "QUAD:GUNB:212:1")
@eles slave_drift_0_11 = Drift(L =  4.30500000000000049E-002)
@eles dg002 = Drift(L =  9.78999999999999870E-002)
@eles vv01b = Drift()
@eles dg003 = Drift(L =  9.70199999999999951E-002)
@eles xc01b = Kicker(Kn0L = -1.00000000000000008E-030, label = "LBNL-xy", alias = "XCOR:GUNB:293")
@eles yc01b = Kicker(Ks0L =  1.00000000000000008E-030, label = "LBNL-xy", alias = "YCOR:GUNB:293")
@eles dg004 = Drift(L =  5.15000000000000006E-003)
@eles bpm1b = Drift(label = "Stripline-4", alias = "BPMS:GUNB:314")
@eles dg005 = Drift(L =  1.05041999999999996E-001)
@eles im01b = Marker(label = "ICT", alias = "TORO:GUNB:360")
@eles dg006 = Drift(L =  7.54080000000000028E-002)
@eles xc02b = Kicker(label = "LBNL-xy", alias = "XCOR:GUNB:388")
@eles yc02b = Kicker(label = "LBNL-xy", alias = "YCOR:GUNB:388")
@eles dg007 = Drift(L =  2.96359999999999957E-002)
@eles bun1b = RFCavity(L =  1.09380000000000005E-001, x1_limit = -2.58500000000000014E-00,
   x2_limit =  2.58500000000000014E-00, y1_limit = -2.58500000000000014E-00,
   y2_limit =  2.58500000000000014E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  1.96884000000000000E+005, phi0 = -2.36111111111111105E-001, label = "LBNL",
   alias = "ACCL:GUNB:455")
@eles dg008 = Drift(L =  4.57039999999999946E-002)
@eles xc03b = Kicker(label = "LBNL-xy", alias = "XCOR:GUNB:513")
@eles yc03b = Kicker(label = "LBNL-xy", alias = "YCOR:GUNB:513")
@eles dg009 = Drift(L =  1.81800999999999990E-001)
@eles am00b = Marker()
@eles dg010 = Drift(L =  2.22999000000000003E-001)
@eles xc04b = Kicker(label = "LBNL-xy", alias = "XCOR:GUNB:713")
@eles yc04b = Kicker(label = "LBNL-xy", alias = "YCOR:GUNB:713")
@eles dg011 = Drift(L =  1.21314000000000005E-001)
@eles yag01b = Drift(label = "YAG", alias = "MOVR:GUNB:753")
@eles yag01b_coll = Drift(label = "collimator")
@eles yag01b_fcup = Marker(label = "Faraday Cup")
@eles dg012a = Drift(L =  5.73499999999999982E-002)
@eles cq02b = Quadrupole(L =  4.53000000000000000E-002, x1_limit = -4.27989999999999968E-00,
   x2_limit =  4.27989999999999968E-00, y1_limit = -4.27989999999999968E-00,
   y2_limit =  4.27989999999999968E-00, label = "3.37Q1.2", alias = "QUAD:GUNB:823:1")
@eles dg012b = Drift(L =  9.39600000000000157E-003)
@eles slave_drift_0_42 = Drift(L =  4.34500000000000164E-002)
@eles sq02b = Multipole(x1_limit = -2.37500000000000003E-00, x2_limit =  2.37500000000000003E-00,
   y1_limit = -2.37500000000000003E-00, y2_limit =  2.37500000000000003E-00, label = "solenoid trim",
   alias = "QUAD:GUNB:823:2")
@eles slave_drift_0_44 = Drift(L =  4.34499999999999886E-002)
@eles dg013 = Drift(L =  9.35200000000000059E-002)
@eles vv02b = Drift()
@eles dg014 = Drift(L =  1.01444000000000006E-001)
@eles bpm2b = Drift(label = "Stripline-4", alias = "BPMS:GUNB:925")
@eles dg015 = Drift(L =  4.53999999999999976E-003)
@eles xc05b = Kicker(label = "LBNL-xy", alias = "XCOR:GUNB:927")
@eles yc05b = Kicker(label = "LBNL-xy", alias = "YCOR:GUNB:927")
@eles dg016a = Drift(L =  8.08449999999999863E-002)
@eles blfu = Marker()
@eles dg016b = Drift(L =  8.29680000000000001E-002)
@eles endgunb = Marker()
@eles begl0b = Marker()
@eles ec1 = Marker()
@eles dcap0u = Drift(L =  4.92939999999999989E-001)
@eles cm01beg = Marker()
@eles dcm1 = Drift(L =  1.47309999999999941E-001)
@eles dcavmap = Drift(L =  1.31128438076923093E-001)
@eles cavl011 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  6.50000000000000000E+006, label = "F1.3-19", alias = "ACCL:L0B:0110")
@eles dcm2 = Drift(L =  8.35999999999998966E-002)
@eles cavl012 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009, label = "F1.3-19",
   alias = "ACCL:L0B:0120")
@eles cavl013 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  9.70000000000000000E+006, label = "F1.3-19", alias = "ACCL:L0B:0130")
@eles cavl014 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  5.00000000000000000E+006, label = "F1.3-19", alias = "ACCL:L0B:0140")
@eles cavl015 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  1.08688035568059999E+007, label = "F1.3-19", alias = "ACCL:L0B:0150")
@eles cavl016 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  1.38786260802292023E+007, label = "F1.3-19", alias = "ACCL:L0B:0160")
@eles cavl017 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  1.38786260802292023E+007, label = "F1.3-19", alias = "ACCL:L0B:0170")
@eles cavl018 = RFCavity(L =  1.03774312384615386E+000, x1_limit = -3.50000000000000033E-00,
   x2_limit =  3.50000000000000033E-00, y1_limit = -3.50000000000000033E-00,
   y2_limit =  3.50000000000000033E-00, rf_frequency =  1.30000000000000000E+009,
   voltage =  1.38786260802292023E+007, label = "F1.3-19", alias = "ACCL:L0B:0180")
@eles dcm3 = Drift(L =  1.61389999999999922E-001)
@eles cmb01 = Drift(label = "cryo F1.3-19", alias = "BPMS:L0B:0183")
@eles dcm4a = Drift(L =  1.19440000000000018E-001)
@eles beam0 = Marker()
@eles dcm4b = Drift(L =  2.99999999999999989E-002)
@eles slave_drift_0_97 = Drift(L =  1.14999999999999797E-001)
@eles ycm01 = Kicker(label = "cryo F1.3-19", alias = "YCOR:L0B:0185")
@eles xcm01 = Kicker(label = "cryo F1.3-19", alias = "XCOR:L0B:0185")
@eles slave_drift_0_100 = Drift(L =  1.15000000000000213E-001)
@eles dcm5 = Drift(L =  2.36860000000000015E-001)
@eles cm01end = Marker()
@eles dcmcm1 = Drift(L =  1.65770000000000001E-001)
@eles homcm01 = Marker()
@eles dcap0da = Drift(L =  3.78512999999999988E-001)
@eles astra = Marker()
@eles dcap0db = Drift(L =  1.34586700000000015E+000)
@eles fc1 = Marker()
@eles dmsc0da = Drift(L =  8.89000000000000068E-002)
@eles blf1 = Marker()
@eles dmsc0db = Drift(L =  1.23189299999999990E+000)
@eles vgl0bd = Marker(label = "gauges")
@eles dmsc0dc = Drift(L =  1.01599999999999996E-001)
@eles vpl0bd = Marker(label = "differential")
@eles dmsc0dd = Drift(L =  1.56407000000000102E-001)
@eles msc0d = Marker()
@eles vvl0bd = Drift(label = "gate valve")
@eles endl0b = Marker()
@eles beghtr = Marker()
@eles d0h00a = Drift(L =  2.50199999999999978E-001)
@eles rfb0h00 = Drift(label = "@2,CavityS-1", alias = "BPMS:HTR:102")
@eles d0h00b = Drift(L =  5.60000000000000012E-002)
@eles pc0h00 = Drift(L =  5.99999999999999978E-002, x1_limit = -6.00000000000000012E-00,
   x2_limit =  6.00000000000000012E-00, y1_limit = -6.00000000000000012E-00,
   y2_limit =  6.00000000000000012E-00, label = "tungsten", alias = "COLL:HTR:103")
@eles d0h00c = Drift(L =  2.91974999999999985E-001)
@eles slave_drift_0_125 = Drift(L =  6.21999999999992975E-002)
@eles bpm0h01 = Drift(label = "Stripline-12", alias = "BPMS:HTR:120")
@eles slave_drift_0_127 = Drift(L =  6.22000000000006992E-002)
@eles d0h01a = Drift(L =  2.13949000000000000E-001)
@eles yc0h01 = Kicker(label = "class-6", alias = "YCOR:HTR:129")
@eles d0h01b = Drift(L =  2.13949000000000000E-001)
@eles q0h02 = Quadrupole(L =  1.24399999999999997E-001, Kn1 =  6.17752713416999999E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:140")
@eles d0h02a = Drift(L =  2.04906000000000005E-001)
@eles xc0h01 = Kicker(label = "class-6", alias = "XCOR:HTR:148")
@eles d0h02b = Drift(L =  9.11460999999999966E-001)
@eles dp0h01 = Marker()
@eles d0h02c = Drift(L =  4.85648000000000024E-001)
@eles dp0h02 = Marker()
@eles d0h02d = Drift(L =  2.07720000000000082E+000)
@eles dp0h03 = Marker()
@eles d0h02e = Drift(L =  2.95093999999999967E-001)
@eles xc0h03 = Kicker(label = "class-6", alias = "XCOR:HTR:288")
@eles d0h02f = Drift(L =  2.04906000000000005E-001)
@eles q0h03 = Quadrupole(L =  1.24399999999999997E-001, Kn1 =  4.83905171962999980E-001,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:300")
@eles d0h03a = Drift(L =  2.04906000000000005E-001)
@eles yc0h03 = Kicker(label = "class-6", alias = "YCOR:HTR:309")
@eles d0h03b = Drift(L =  2.04906000000000005E-001)
@eles slave_drift_0_147 = Drift(L =  6.21999999999992975E-002)
@eles bpm0h04 = Drift(label = "Stripline-12", alias = "BPMS:HTR:320")
@eles slave_drift_0_149 = Drift(L =  6.22000000000006992E-002)
@eles d0h04a = Drift(L =  2.14799999999999991E-001)
@eles rfb0h04 = Drift(label = "@2,CavityS-1", alias = "BPMS:HTR:325")
@eles d0h04b = Drift(L =  3.33000000000000032E-002)
@eles otr0h04 = Drift(label = "OTR", alias = "OTRS:HTR:330")
@eles otr0h04_yag = Drift(label = "YAG")
@eles d0h04c = Drift(L =  2.43700000000000000E-001)
@eles ws0h04 = Marker(label = "fast", alias = "WIRE:HTR:340")
@eles d0h04d = Drift(L =  2.49200000000000005E-001)
@eles bz0h04 = Drift(label = "gap/diode", alias = "BLEN:HTR:350")
@eles d0h04e = Drift(L =  3.56900000000000106E-001)
@eles slave_drift_0_160 = Drift(L =  6.21999999999992975E-002)
@eles bpm0h05 = Drift(label = "Stripline-12", alias = "BPMS:HTR:365")
@eles slave_drift_0_162 = Drift(L =  6.22000000000006992E-002)
@eles d0h05a = Drift(L =  2.04906000000000005E-001)
@eles yc0h05 = Kicker(label = "class-6", alias = "YCOR:HTR:377")
@eles d0h05b = Drift(L =  2.04906000000000005E-001)
@eles q0h06 = Quadrupole(L =  1.24399999999999997E-001, x1_limit = -2.69000000000000003E-00,
   x2_limit =  2.69000000000000003E-00, y1_limit = -2.69000000000000003E-00,
   y2_limit =  2.69000000000000003E-00, label = "2Q4", alias = "QUAD:HTR:385")
@eles d0h06a = Drift(L =  2.04906000000000005E-001)
@eles xc0h05 = Kicker(label = "class-6", alias = "XCOR:HTR:396")
@eles d0h06b = Drift(L =  9.56264000000000003E-001)
@eles xc0h07 = Kicker(label = "class-6", alias = "XCOR:HTR:428")
@eles d0h06c = Drift(L =  2.04906000000000005E-001)
@eles q0h07 = Quadrupole(L =  1.24399999999999997E-001, Kn1 =  5.84302489781000034E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:440")
@eles d0h07a = Drift(L =  2.04906000000000005E-001)
@eles yc0h07 = Kicker(label = "class-6", alias = "YCOR:HTR:451")
@eles d0h07b = Drift(L =  2.04906000000000005E-001)
@eles slave_drift_0_176 = Drift(L =  6.21999999999992975E-002)
@eles bpm0h08 = Drift(label = "Stripline-12", alias = "BPMS:HTR:460")
@eles slave_drift_0_178 = Drift(L =  6.22000000000006992E-002)
@eles d0h08a = Drift(L =  1.93399999999999989E-001)
@eles rfb0h08 = Drift(label = "@2,CavityS-1", alias = "BMPS:HTR:475")
@eles d0h08b = Drift(L =  1.75300000000000039E-001)
@eles lhbegb = Marker()
@eles bcxh1 = SBend(L =  1.24410139414978096E-001, e2 =  2.21136023169999987E-002,
   g =  1.77747588910246640E-001, label = "5D3.9", alias = "BEND:HTR:480")
@eles dh01a = Drift(L =  1.53779927537186478E+000, label = "CSR")
@eles bpmh1 = Drift(label = "Stripline-8", alias = "BPMS:HTR:540")
@eles dh01b = Drift(L =  3.75708569144652338E-001, label = "CSR")
@eles mirlhu = Marker(label = "laser inj/ext")
@eles dh01c = Drift(L =  1.35222440420540613E+000, label = "CSR")
@eles bcxh2 = SBend(L =  1.24410139414978096E-001, e1 = -2.21136023169999987E-002,
   g = -1.77747588910246640E-001, label = "5D3.9", alias = "BEND:HTR:600")
@eles dh02a = Drift(L =  1.62614000000000009E-001, label = "CSR")
@eles cehtr = Drift(L =  5.99999999999999978E-002, x1_limit = -3.00000000000000006E-00,
   x2_limit =  3.00000000000000006E-00, label = "HCOLL", alias = "COLL:HTR:615")
@eles dh02b = Drift(L =  2.68449999999999966E-001, label = "CSR")
@eles yagh1 = Drift(label = "YAG INJ", alias = "YAGS:HTR:625")
@eles dh02c = Drift(L =  2.89638000000000007E-001, label = "CSR")
@eles htrundb = Marker(label = "SCATTER")
@eles dh02d = Drift(L =  2.82602200000000026E-001, label = "CSR")
@eles yagh2 = Drift(label = "YAG INJ", alias = "YAGS:HTR:675")
@eles dh02e = Drift(L =  4.59999800000000014E-001, label = "CSR")
@eles bcxh3 = SBend(L =  1.24410139414978096E-001, e2 = -2.21136023169999987E-002,
   g = -1.77747588910246640E-001, label = "5D3.9", alias = "BEND:HTR:700")
@eles dh03a = Drift(L =  1.39033413967538255E+000, label = "CSR")
@eles mirlhd = Marker(label = "laser inj/ext")
@eles dh03b = Drift(L =  3.37598833674676024E-001, label = "CSR")
@eles bpmh2 = Drift(label = "Stripline-8", alias = "BPMS:HTR:760")
@eles dh03c = Drift(L =  1.53779927537186478E+000, label = "CSR")
@eles bcxh4 = SBend(L =  1.24410139414978096E-001, e1 =  2.21136023169999987E-002,
   g =  1.77747588910246640E-001, label = "5D3.9", alias = "BEND:HTR:820")
@eles cnthtr = Marker(label = "CENTER")
@eles lhendb = Marker()
@eles dhd00a = Drift(L =  2.81398817802000045E-001)
@eles rfbhd00 = Drift(label = "@2,CavityS-1", alias = "BPMS:HTR:825")
@eles dhd00b = Drift(L =  1.00000000000000006E-001)
@eles slave_drift_0_213 = Drift(L =  6.22000000000028502E-002)
@eles bpmhd01 = Drift(label = "Stripline-12", alias = "BPMS:HTR:830")
@eles slave_drift_0_215 = Drift(L =  6.21999999999971465E-002)
@eles dhd01a = Drift(L =  2.04906000000000005E-001)
@eles ychd01 = Kicker(label = "class-6", alias = "YCOR:HTR:841")
@eles dhd01b = Drift(L =  2.46787999999999924E-001)
@eles xchd01 = Kicker(label = "class-6", alias = "XCOR:HTR:848")
@eles dhd01c = Drift(L =  2.04906000000000005E-001)
@eles slave_drift_0_221 = Drift(L =  6.22000000000028502E-002)
@eles bpmhd02 = Drift(label = "Stripline-12", alias = "BPMS:HTR:860")
@eles slave_drift_0_223 = Drift(L =  6.21999999999971465E-002)
@eles dhd02a1 = Drift(L =  1.29277800000000020E+000)
@eles imbcsi1 = Marker(label = "BCS ACM", alias = "ACM:HTR:910")
@eles dhd02a2 = Drift(L =  3.05410000000000015E-001)
@eles imbcsi2 = Marker(label = "BCS ACM", alias = "ACM:HTR:922")
@eles dhd02a3 = Drift(L =  7.77294000000000040E-001)
@eles ychd03 = Kicker(label = "class-6", alias = "YCOR:HTR:951")
@eles dhd02b = Drift(L =  2.04906000000000005E-001)
@eles slave_drift_0_231 = Drift(L =  6.21999999999957448E-002)
@eles bpmhd03 = Drift(label = "Stripline-12", alias = "BPMS:HTR:960")
@eles slave_drift_0_233 = Drift(L =  6.22000000000042519E-002)
@eles dhd03a = Drift(L =  2.54905999999999966E-001)
@eles xchd03 = Kicker(label = "class-6", alias = "XCOR:HTR:974")
@eles dhd03b = Drift(L =  2.04906000000000005E-001)
@eles slave_drift_0_237 = Drift(L =  6.22000000000028502E-002)
@eles bpmhd04 = Drift(label = "Stripline-12", alias = "BPMS:HTR:980")
@eles slave_drift_0_239 = Drift(L =  6.21999999999971465E-002)
@eles dhd04a = Drift(L =  1.20899800000000002E-001)
@eles rfbhd04 = Drift(label = "@2,CavityS-1", alias = "BPMS:HTR:990")
@eles dhd04b = Drift(L =  2.47899800000000003E-001)
@eles endhtr = Marker()
@eles begdiag0 = Marker()
@eles bkrdg0 = SBend(L =  1.00001157374365057E+000, e2 = -8.33318062396000078E-003,
   g = -8.33308417897989442E-003, tilt_ref =  1.74749576742289658E+000, label = "1.378K35.4",
   alias = "KICK:DIAG0:110")
@eles rodg0k = Patch(tilt = -6.00843383730000019E-006)
@eles dkv0a = Drift(L =  6.48927504243820286E-001)
@eles bpmdg000 = Drift(label = "Stripline-4", alias = "BPMS:COL0:135")
@eles dkv0b = Drift(L =  6.51117634296775494E-001)
@eles m1dg0 = Marker()
@eles blrdg0 = SBend(L =  4.00748297099801976E-001, e2 =  1.04888536537999996E-001,
   g =  2.61731708648729855E-001, tilt_ref =  1.76699440627999999E-001, label = "0.79SD14.96",
   alias = "BEND:DIAG0:155")
@eles rodg0l = Patch(tilt =  1.05498270761000004E-004)
@eles dqb01a = Drift(L =  1.49999999999999994E-001)
@eles rfbdg001 = Drift(label = "@2,CavityL-1", alias = "BPMS:DIAG0:160")
@eles dqb01b = Drift(L =  8.02327050328480063E-001)
@eles xcdg001 = Kicker(label = "class-6", alias = "XCOR:DIAG0:178")
@eles dqb01c = Drift(L =  2.50000000000000000E-001)
@eles slave_drift_0_258 = Drift(L =  9.84999999999986442E-002)
@eles bpmdg001 = Drift(label = "Stripline-9", alias = "BPMS:DIAG0:190")
@eles dyqdg001 = Patch(x_rot =  9.49758257820075558E-003)
@eles slave_drift_0_261 = Drift(L =  9.85000000000013642E-002)
@eles dqb02a = Drift(L =  4.14820863279852237E-001)
@eles ycdg001 = Kicker(label = "class-6", alias = "YCOR:DIAG0:199")
@eles dqb02b = Drift(L =  2.50000000000000000E-001)
@eles slave_drift_0_265 = Drift(L =  9.84999999999986442E-002)
@eles bpmdg002 = Drift(label = "Stripline-9", alias = "BPMS:DIAG0:210")
@eles slave_drift_0_267 = Drift(L =  9.85000000000013642E-002)
@eles dqb03a = Drift(L =  4.14820863279852237E-001)
@eles xcdg002 = Kicker(label = "class-6", alias = "XCOR:DIAG0:218")
@eles dqb03b = Drift(L =  2.50000000000000000E-001)
@eles slave_drift_0_271 = Drift(L =  9.84999999999986442E-002)
@eles bpmdg003 = Drift(label = "Stripline-9", alias = "BPMS:DIAG0:230")
@eles dyqdg003 = Patch(x_rot =  5.88487966838956720E-004)
@eles slave_drift_0_274 = Drift(L =  9.85000000000013642E-002)
@eles dqb04a = Drift(L =  7.78428507705855033E-001)
@eles ycdg002 = Kicker(label = "class-6", alias = "YCOR:DIAG0:247")
@eles dqb04b = Drift(L =  4.53199999999999992E-001)
@eles bxdg0 = SBend(L =  4.00182828927592549E-001, e1 = -5.23598775598298899E-002,
   e2 = -5.23598775598298899E-002, g = -2.61679781214719076E-001, label = "0.79D14.96",
   alias = "BEND:DIAG0:260")
@eles cntdg0 = Marker(label = "CENTER")
@eles m2dg0 = Marker()
@eles ddg003 = Drift(L =  3.74418820857999990E-001)
@eles slave_drift_0_282 = Drift(L =  5.39999999999979524E-002)
@eles bpmdg004 = Drift(label = "Stripline-1", alias = "BPMS:DIAG0:270")
@eles slave_drift_0_284 = Drift(L =  5.40000000000020464E-002)
@eles ddg004a = Drift(L =  2.70500000000000018E-001)
@eles xcdg003 = Kicker(label = "class-1a", alias = "XCOR:DIAG0:280")
@eles ycdg003 = Kicker(label = "class-1a", alias = "YCOR:DIAG0:280")
@eles ddg004b = Drift(L =  2.70500000000000018E-001)
@eles slave_drift_0_289 = Drift(L =  5.40000000000050578E-002)
@eles bpmdg005 = Drift(label = "Stripline-1", alias = "BPMS:DIAG0:285")
@eles slave_drift_0_291 = Drift(L =  5.39999999999949409E-002)
@eles ddg005a = Drift(L =  2.95999999999999985E-001)
@eles xcdg005 = Kicker(label = "class-1a", alias = "XCOR:DIAG0:290")
@eles ycdg005 = Kicker(label = "class-1a", alias = "YCOR:DIAG0:290")
@eles ddg005b = Drift(L =  2.95999999999999985E-001)
@eles qdg006 = Quadrupole(L =  1.07999999999999999E-001, Kn1 =  6.83063973310400030E+000,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:300")
@eles ddg006a = Drift(L =  7.32751400000000053E-001)
@eles slave_drift_0_298 = Drift(L =  2.54000000000002224E-001)
@eles mtcydg0 = Marker()
@eles ycdgtcy = Kicker(label = "@4,class-1t", alias = "YCOR:DIAG0:320")
@eles xcdgtcy = Kicker(label = "@4,class-1t", alias = "XCOR:DIAG0:320")
@eles slave_drift_0_302 = Drift(L =  2.53999999999997783E-001)
@eles ddg006b = Drift(L =  1.27140000000000003E-001)
@eles bpmdg0rf = Drift(label = "Stripline-1", alias = "BPMS:DIAG0:330")
@eles ddg006c = Drift(L =  1.72860000000000014E-001)
@eles slave_drift_0_306 = Drift(L =  2.53999999999995119E-001)
@eles mtcxdg0 = Marker()
@eles ycdgtcx = Kicker(label = "class-1t", alias = "YCOR:DIAG0:340")
@eles xcdgtcx = Kicker(label = "class-1t", alias = "XCOR:DIAG0:340")
@eles slave_drift_0_310 = Drift(L =  2.54000000000004889E-001)
@eles ddg006d = Drift(L =  4.87248599999999810E-001)
@eles qdg007 = Quadrupole(L =  1.07999999999999999E-001, Kn1 = -4.54371250975500018E+000,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:360")
@eles ddg007 = Drift(L =  5.48000000000000043E-001)
@eles slave_drift_0_314 = Drift(L =  5.39999999999979524E-002)
@eles bpmdg008 = Drift(label = "Stripline-1", alias = "BPMS:DIAG0:370")
@eles slave_drift_0_316 = Drift(L =  5.40000000000020464E-002)
@eles ddg008a = Drift(L =  2.95999999999999985E-001)
@eles xcdg008 = Kicker(label = "class-1a", alias = "XCOR:DIAG0:380")
@eles ycdg008 = Kicker(label = "class-1a", alias = "YCOR:DIAG0:380")
@eles ddg008b = Drift(L =  2.95999999999999985E-001)
@eles slave_drift_0_321 = Drift(L =  5.40000000000050578E-002)
@eles bpmdg009 = Drift(label = "Stripline-1", alias = "BPMS:DIAG0:390")
@eles slave_drift_0_323 = Drift(L =  5.39999999999949409E-002)
@eles ddg009a = Drift(L =  2.95999999999999985E-001)
@eles otrdg01 = Drift(label = "@3,OTR", alias = "OTRS:DIAG0:396")
@eles otrdg01_yag = Drift(label = "@3,YAG")
@eles ddg009b = Drift(L =  6.99999999999999956E-001)
@eles rfbdg002 = Drift(label = "@2,CavityS-1", alias = "BPMS:DIAG0:410")
@eles ddg009c = Drift(L =  2.99999999999999989E-001)
@eles otrdg02 = Drift(label = "OTR INJ", alias = "OTRS:DIAG0:420")
@eles ddg009d = Drift(L =  2.99999999999999989E-001)
@eles wsdg01 = Marker(label = "slow", alias = "WIRE:DIAG0:424")
@eles ddg009e = Drift(L =  6.99999999999999956E-001)
@eles otrdg03 = Drift(label = "@3,OTR", alias = "OTRS:DIAG0:440")
@eles otrdg03_yag = Drift(label = "@3,YAG")
@eles ddg009f = Drift(L =  6.66000000000000369E-001)
@eles qdg010 = Quadrupole(L =  1.07999999999999999E-001, Kn1 =  1.30166515488099996E+001,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:455")
@eles ddg010a = Drift(L =  2.95999999999999985E-001)
@eles xcdg010 = Kicker(label = "class-1a", alias = "XCOR:DIAG0:460")
@eles ycdg010 = Kicker(label = "class-1a", alias = "YCOR:DIAG0:460")
@eles ddg010b = Drift(L =  2.95999999999999985E-001)
@eles slave_drift_0_342 = Drift(L =  5.39999999999979524E-002)
@eles bpmdg011 = Drift(label = "Stripline-1", alias = "BPMS:DIAG0:470")
@eles slave_drift_0_344 = Drift(L =  5.40000000000020464E-002)
@eles ddg011a = Drift(L =  2.99999999999999989E-001)
@eles rfbdg003 = Drift(label = "@2,CavityS-1", alias = "BPMS:DIAG0:480")
@eles ddg011b = Drift(L =  1.10480000000000000E+000)
@eles bydg0 = SBend(L =  5.43499999999999983E-001, e1 = -1.27234502470386618E-001,
   e2 = -1.27234502470386618E-001, g = -1.12394708040113223E+000, tilt_ref =  1.57079632679489656E+000,
   label = "BXS", alias = "BEND:DIAG0:510")
@eles ddg012a = Drift(L =  3.95296300378999987E-001)
@eles bpmdg012 = Drift(label = "Stripline-11", alias = "BPMS:DIAG0:520")
@eles ddg012b = Drift(L =  2.39999999999999991E-001)
@eles otrdg04 = Drift(label = "OTR INJ", alias = "OTRS:DIAG0:525")
@eles ddg012c = Drift(L =  3.00000000000000044E-001)
@eles fcdg0du = Marker(label = "Faraday cup", alias = "FARC:DIAG0:530")
@eles enddiag0 = Marker()
@eles end1 = Marker()
@eles qcm01 = Quadrupole(L =  2.30000000000000010E-001, x1_limit = -3.81000000000000019E-00,
   x2_limit =  3.81000000000000019E-00, y1_limit = -3.81000000000000019E-00,
   y2_limit =  3.81000000000000019E-00, label = "cryo SPQA127", alias = "QUAD:L0B:0185")
@eles qdg001 = Quadrupole(L =  1.97000000000000008E-001, Kn1 =  9.80742587143200240E+000,
   x1_limit = -1.91769999999999996E-00, x2_limit =  1.91769999999999996E-00,
   y1_limit = -1.91769999999999996E-00, y2_limit =  1.91769999999999996E-00,
   y_offset = -4.83865231890650768E-003, label = "1.51Q7.00", alias = "QUAD:DIAG0:190")
@eles qdg003 = Quadrupole(L =  1.97000000000000008E-001, Kn1 =  9.80742587143200240E+000,
   x1_limit = -1.91769999999999996E-00, x2_limit =  1.91769999999999996E-00,
   y1_limit = -1.91769999999999996E-00, y2_limit =  1.91769999999999996E-00,
   y_offset = -2.99813063290814820E-004, label = "1.51Q7.00", alias = "QUAD:DIAG0:230")
@eles qdg002 = Quadrupole(L =  1.97000000000000008E-001, Kn1 = -7.82514055648799989E+000,
   x1_limit = -1.91769999999999996E-00, x2_limit =  1.91769999999999996E-00,
   y1_limit = -1.91769999999999996E-00, y2_limit =  1.91769999999999996E-00, label = "1.51Q7.00",
   alias = "QUAD:DIAG0:210")
@eles qdg004 = Quadrupole(L =  1.07999999999999999E-001, Kn1 =  8.77167762187499989E+000,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:270")
@eles qdg005 = Quadrupole(L =  1.07999999999999999E-001, Kn1 = -1.20531892994910006E+001,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:285")
@eles qdg008 = Quadrupole(L =  1.07999999999999999E-001, Kn1 =  1.13770274353089995E+001,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:370")
@eles qdg009 = Quadrupole(L =  1.07999999999999999E-001, Kn1 = -1.15392296425869993E+001,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:390")
@eles qdg011 = Quadrupole(L =  1.07999999999999999E-001, Kn1 = -1.09836509817210004E+001,
   x1_limit = -1.60000000000000003E-00, x2_limit =  1.60000000000000003E-00,
   y1_limit = -1.60000000000000003E-00, y2_limit =  1.60000000000000003E-00, label = "1.26Q3.5",
   alias = "QUAD:DIAG0:470")
@eles sol1b = Solenoid(L =  8.60999999999999960E-002, x1_limit = -2.37500000000000003E-00,
   x2_limit =  2.37500000000000003E-00, y1_limit = -2.37500000000000003E-00,
   y2_limit =  2.37500000000000003E-00, label = "LBNL", alias = "SOLN:GUNB:212")
@eles sol2b = Solenoid(L =  8.69000000000000050E-002, x1_limit = -2.37500000000000003E-00,
   x2_limit =  2.37500000000000003E-00, y1_limit = -2.37500000000000003E-00,
   y2_limit =  2.37500000000000003E-00, label = "LBNL", alias = "SOLN:GUNB:823")
@eles q0h01 = Quadrupole(L =  1.24399999999999997E-001, Kn1 = -6.53777756473600036E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:120")
@eles q0h04 = Quadrupole(L =  1.24399999999999997E-001, Kn1 = -3.97157540215699978E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:320")
@eles q0h05 = Quadrupole(L =  1.24399999999999997E-001, Kn1 = -2.32266979602000001E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:365")
@eles q0h08 = Quadrupole(L =  1.24399999999999997E-001, Kn1 = -5.21025845476100002E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:460")
@eles qhd01 = Quadrupole(L =  1.24399999999999997E-001, Kn1 = -1.31785985802370007E+001,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:830")
@eles qhd02 = Quadrupole(L =  1.24399999999999997E-001, Kn1 =  7.65066841088400018E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:860")
@eles qhd03 = Quadrupole(L =  1.24399999999999997E-001, Kn1 = -7.97893497238499982E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:960")
@eles qhd04 = Quadrupole(L =  1.24399999999999997E-001, Kn1 =  6.23868208953200121E+000,
   x1_limit = -2.69000000000000003E-00, x2_limit =  2.69000000000000003E-00,
   y1_limit = -2.69000000000000003E-00, y2_limit =  2.69000000000000003E-00, label = "2Q4",
   alias = "QUAD:HTR:980")


sc_diag0 = Beamline([ beggunb, dgbca, sol1bkb, dgbcb, cathodeb, dgun, dg001, slave_drift_0_8, sq01b,
   cq01b, slave_drift_0_11, dg002, vv01b, dg003, xc01b, yc01b, dg004, bpm1b, dg005, im01b, dg006, xc02b,
   yc02b, dg007, bun1b, bun1b, dg008, xc03b, yc03b, dg009, am00b, dg010, xc04b, yc04b, dg011, yag01b,
   yag01b_coll, yag01b_fcup, dg012a, cq02b, dg012b, slave_drift_0_42, sq02b, slave_drift_0_44, dg013,
   vv02b, dg014, bpm2b, dg015, xc05b, yc05b, dg016a, blfu, dg016b, endgunb, begl0b, ec1, dcap0u, cm01beg,
   dcm1, dcavmap, cavl011, dcavmap, dcm2, dcavmap, cavl012, dcavmap, dcm2, dcavmap, cavl013, dcavmap, dcm2,
   dcavmap, cavl014, dcavmap, dcm2, dcavmap, cavl015, dcavmap, dcm2, dcavmap, cavl016, dcavmap, dcm2,
   dcavmap, cavl017, dcavmap, dcm2, dcavmap, cavl018, dcavmap, dcm3, cmb01, dcm4a, beam0, dcm4b,
   slave_drift_0_97, ycm01, xcm01, slave_drift_0_100, dcm5, cm01end, dcmcm1, homcm01, dcap0da, astra,
   dcap0db, fc1, dmsc0da, blf1, dmsc0db, vgl0bd, dmsc0dc, vpl0bd, dmsc0dd, msc0d, vvl0bd, endl0b, beghtr,
   d0h00a, rfb0h00, d0h00b, pc0h00, d0h00c, slave_drift_0_125, bpm0h01, slave_drift_0_127, d0h01a, yc0h01,
   d0h01b, q0h02, d0h02a, xc0h01, d0h02b, dp0h01, d0h02c, dp0h02, d0h02d, dp0h03, d0h02e, xc0h03, d0h02f,
   q0h03, d0h03a, yc0h03, d0h03b, slave_drift_0_147, bpm0h04, slave_drift_0_149, d0h04a, rfb0h04, d0h04b,
   otr0h04, otr0h04_yag, d0h04c, ws0h04, d0h04d, bz0h04, d0h04e, slave_drift_0_160, bpm0h05,
   slave_drift_0_162, d0h05a, yc0h05, d0h05b, q0h06, d0h06a, xc0h05, d0h06b, xc0h07, d0h06c, q0h07, d0h07a,
   yc0h07, d0h07b, slave_drift_0_176, bpm0h08, slave_drift_0_178, d0h08a, rfb0h08, d0h08b, lhbegb, bcxh1,
   dh01a, bpmh1, dh01b, mirlhu, dh01c, bcxh2, dh02a, cehtr, dh02b, yagh1, dh02c, htrundb,
   dh02d, yagh2, dh02e, bcxh3, dh03a, mirlhd, dh03b, bpmh2, dh03c, bcxh4, cnthtr, lhendb, dhd00a, rfbhd00,
   dhd00b, slave_drift_0_213, bpmhd01, slave_drift_0_215, dhd01a, ychd01, dhd01b, xchd01, dhd01c,
   slave_drift_0_221, bpmhd02, slave_drift_0_223, dhd02a1, imbcsi1, dhd02a2, imbcsi2, dhd02a3, ychd03,
   dhd02b, slave_drift_0_231, bpmhd03, slave_drift_0_233, dhd03a, xchd03, dhd03b, slave_drift_0_237,
   bpmhd04, slave_drift_0_239, dhd04a, rfbhd04, dhd04b, endhtr, begdiag0, bkrdg0, rodg0k, dkv0a, bpmdg000,
   dkv0b, m1dg0, blrdg0, rodg0l, dqb01a, rfbdg001, dqb01b, xcdg001, dqb01c, slave_drift_0_258, bpmdg001,
   dyqdg001, slave_drift_0_261, dqb02a, ycdg001, dqb02b, slave_drift_0_265, bpmdg002, slave_drift_0_267,
   dqb03a, xcdg002, dqb03b, slave_drift_0_271, bpmdg003, dyqdg003, slave_drift_0_274, dqb04a, ycdg002,
   dqb04b, bxdg0, cntdg0, m2dg0, ddg003, slave_drift_0_282, bpmdg004, slave_drift_0_284, ddg004a, xcdg003,
   ycdg003, ddg004b, slave_drift_0_289, bpmdg005, slave_drift_0_291, ddg005a, xcdg005, ycdg005, ddg005b,
   qdg006, ddg006a, slave_drift_0_298, mtcydg0, ycdgtcy, xcdgtcy, slave_drift_0_302, ddg006b, bpmdg0rf,
   ddg006c, slave_drift_0_306, mtcxdg0, ycdgtcx, xcdgtcx, slave_drift_0_310, ddg006d, qdg007, ddg007,
   slave_drift_0_314, bpmdg008, slave_drift_0_316, ddg008a, xcdg008, ycdg008, ddg008b, slave_drift_0_321,
   bpmdg009, slave_drift_0_323, ddg009a, otrdg01, otrdg01_yag, ddg009b, rfbdg002, ddg009c, otrdg02,
   ddg009d, wsdg01, ddg009e, otrdg03, otrdg03_yag, ddg009f, qdg010, ddg010a, xcdg010, ycdg010, ddg010b,
   slave_drift_0_342, bpmdg011, slave_drift_0_344, ddg011a, rfbdg003, ddg011b, bydg0, ddg012a, bpmdg012,
   ddg012b, otrdg04, ddg012c, fcdg0du, enddiag0, end1]; pc_ref =  1.15282194029910816E+006,
   species_ref = Species("electron"))

