
const PROPERTIES_MAP = Dict{Symbol,Type{<:AbstractParams}}(
  :tilt0 =>  BMultipoleParams,
  :tilt1 =>  BMultipoleParams,
  :tilt2 =>  BMultipoleParams,
  :tilt3 =>  BMultipoleParams,
  :tilt4 =>  BMultipoleParams,
  :tilt5 =>  BMultipoleParams,
  :tilt6 =>  BMultipoleParams,
  :tilt7 =>  BMultipoleParams,
  :tilt8 =>  BMultipoleParams,
  :tilt9 =>  BMultipoleParams,
  :tilt10 => BMultipoleParams,
  :tilt11 => BMultipoleParams,
  :tilt12 => BMultipoleParams,
  :tilt13 => BMultipoleParams,
  :tilt14 => BMultipoleParams,
  :tilt15 => BMultipoleParams,
  :tilt16 => BMultipoleParams,
  :tilt17 => BMultipoleParams,
  :tilt18 => BMultipoleParams,
  :tilt19 => BMultipoleParams,
  :tilt20 => BMultipoleParams,
  :tilt21 => BMultipoleParams,

  :L => UniversalParams,
  :tracking_method => UniversalParams,
  :kind => UniversalParams,
  :name => UniversalParams,

  :beamline => BeamlineParams,
  :beamline_index => BeamlineParams,
  #= These guys now virtual for InitialBeamlineParams
  :R_ref => BeamlineParams, 
  :E_ref => BeamlineParams, 
  :pc_ref => BeamlineParams, 
  :dR_ref => BeamlineParams, 
  :dE_ref => BeamlineParams, 
  :dpc_ref => BeamlineParams, 
  :species_ref => BeamlineParams,
  =#
  :lattice => BeamlineParams,
  :lattice_index => BeamlineParams,
  :s => BeamlineParams,
  :s_downstream => BeamlineParams,

  :g_ref => BendParams,
  :tilt_ref => BendParams,
  :e1 => BendParams,
  :e2 => BendParams,
  :edge1_int => BendParams,
  :edge2_int => BendParams,

  :x_offset => AlignmentParams,
  :y_offset => AlignmentParams,
  :z_offset => AlignmentParams,
  :x_rot => AlignmentParams,
  :y_rot => AlignmentParams,
  :tilt => AlignmentParams,

  :dt => PatchParams,
  :dx => PatchParams,
  :dy => PatchParams,
  :dz => PatchParams,
  :dx_rot => PatchParams,
  :dy_rot => PatchParams,
  :dz_rot => PatchParams,

  :x1_limit         => ApertureParams,
  :x2_limit         => ApertureParams,
  :y1_limit         => ApertureParams,
  :y2_limit         => ApertureParams,
  :aperture_shape   => ApertureParams,
  :aperture_at      => ApertureParams,
  :aperture_shifts_with_body => ApertureParams,
  :aperture_active  => ApertureParams,

  :voltage => RFParams,
  :phi0 => RFParams,
  :harmon_master => RFParams,
  :zero_phase => RFParams,
  :traveling_wave => RFParams,
  :is_crabcavity => RFParams,

  :transport_map => MapParams,
  :four_potential => FourPotentialParams,
  
  :alias => MetaParams,
  :label => MetaParams,
  :description => MetaParams,
)

const PARAMS_MAP = Dict{Symbol,Type{<:AbstractParams}}(
  :BMultipoleParams => BMultipoleParams,
  :UniversalParams => UniversalParams,
  :BeamlineParams => BeamlineParams,
  :BendParams => BendParams,
  :AlignmentParams => AlignmentParams,
  :PatchParams => PatchParams,
  :RFParams => RFParams,
  :ApertureParams => ApertureParams,
  :MapParams => MapParams,
  :FourPotentialParams => FourPotentialParams,
  :MetaParams => MetaParams,
)